export const icons = {
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 sprout:'<path d="M12 22v-9M12 17C4 17 2 12 2 6c6 0 10 3 10 9M12 13c0-7 4-11 10-11 0 6-3 11-10 11"/>',
 sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3ZM3 2v4M1 4h4M21 18v4M19 20h4"/>',
 people:'<circle cx="9" cy="7" r="4"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M17 3a4 4 0 0 1 0 8M22 21v-3a7 7 0 0 0-4-6"/>',
 compass:'<circle cx="12" cy="12" r="10"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',
 palette:'<path d="M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 0-4 2 2 0 0 1 0-4h4a4 4 0 0 0 4-4c0-3-4-6-9-6Z"/><path d="M7 8h.01M11 6h.01M16 7h.01M5 13h.01" stroke-width="3"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2M12 21v2M1 12h2M21 12h2M4 4l1.5 1.5M18.5 18.5 20 20M20 4l-1.5 1.5M5.5 18.5 4 20"/>',
 chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-3 2 2-6A8.5 8.5 0 1 1 21 11.5Z"/><path d="M7 9h9M7 13h6"/>',
 book:'<path d="M12 5c-3-3-8-3-10-2v16c4-1 7-1 10 2 3-3 6-3 10-2V3c-4-1-7-1-10 2ZM12 5v16"/>',
 blocks:'<rect x="2" y="12" width="9" height="9" rx="1"/><rect x="13" y="12" width="9" height="9" rx="1"/><rect x="7" y="1" width="9" height="9" rx="1"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 star:'<path d="m12 2 3.1 6.3L22 9.3l-5 4.9 1.2 6.8-6.2-3.2L5.8 21 7 14.2l-5-4.9 6.9-1L12 2Z"/>'
};
export const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.sparkles}</svg>`;
export const programs=[
 {id:'playgroup',name:'Playgroup',age:'2–3 years',filter:'2',color:'peach',icon:'blocks',intro:'First friends, little discoveries and a gentle introduction to learning together.',detail:'A gentle start to being part of a group, with plenty of play and encouragement.',skills:['Sensory play and exploration','Simple stories, songs and rhymes','Finding comfort in a new routine']},
 {id:'nursery',name:'Nursery',age:'3–4 years',filter:'3',color:'mint',icon:'sprout',intro:'Curious questions, creative play and a growing world of “I can do it!”',detail:'A happy space to ask questions, try new things and find a little more independence.',skills:['Language through stories and conversation','Sorting, matching and early number play','Creative expression and new friendships']},
 {id:'junior-kg',name:'Junior KG',age:'4–5 years',filter:'4',color:'lavender',icon:'palette',intro:'Big imaginations, new ideas and confident steps into early learning.',detail:'Connecting ideas through hands-on experiences, early literacy and purposeful play.',skills:['Early sounds, letters and number concepts','Fine motor skills through art and making','Cooperation, problem-solving and expression']},
 {id:'senior-kg',name:'Senior KG',age:'5–6 years',filter:'5',color:'sky',icon:'book',intro:'Building independence and a love of learning for the next big adventure.',detail:'Growing confidence, independence and the foundations for a positive transition to school.',skills:['Building on early literacy and numeracy','Following routines and expressing ideas','Working together and trying independently']}
];
const brand=`<a class="brand" href="/" aria-label="Kinder Joy Preschool home"><img src="/assets/logo.webp" alt="Kinder Joy children on a pencil logo" width="78" height="68"><span><span class="brand-title"><span>K</span><span>i</span><span>n</span><span>der</span> <span>Joy</span></span><small>PRESCHOOL</small></span></a>`;
export function header(page){const links=[['/','Home','home'],['/our-story','Our Story','story'],['/programs','Programs','programs'],['/#a-day-here','A Day Here','day'],['/admissions','Admissions','admissions']].map(([url,title,key])=>`<a href="${url}"${page===key?' aria-current="page"':''}>${title}</a>`).join('');return `<a class="skip-link" href="#main">Skip to content</a><div class="announcement">Little steps. Big discoveries. <span class="spark" aria-hidden="true">✦</span> A happy childhood starts here.</div><header class="site-header"><div class="container nav-row">${brand}<nav class="desktop-nav" aria-label="Main navigation">${links}</nav><button class="button primary small nav-visit" data-visit>Book a Visit <span aria-hidden="true">↗</span></button><button class="menu-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu">${icon('menu')}</button></div><nav class="mobile-nav" id="mobile-menu" aria-label="Mobile navigation" hidden>${links}<button class="button primary small" data-visit>Book a Visit ↗</button></nav></header>`;}
export const footer=`<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand">${brand}<p>Each child is unique for us.<br>A little world of learning, laughter and love. Since 2018.</p></div><div><h3>Explore Kinder Joy</h3><nav class="footer-links" aria-label="Footer"><a href="/our-story">Our story</a><a href="/programs">Our programs</a><a href="/#a-day-here">A day here</a><a href="/admissions">Admissions</a></nav></div><div><h3>Little learning journeys</h3><nav class="footer-links" aria-label="Programs">${programs.map(p=>`<a href="/programs#${p.id}">${p.name}</a>`).join('')}</nav></div><div class="footer-invite"><h3>Let's make a happy start.</h3><p>The best way to get to know us? Start with a little hello.</p><a href="/admissions">Say hello to Kinder Joy ↗</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Kinder Joy Preschool. Made for wonderful beginnings.</span><div><a href="/privacy">Enquiry privacy</a><a href="/admin">School desk</a></div></div></div></footer>`;
export const cta=`<section class="cta-wrap"><div class="container"><div class="cta-card"><div><span class="eyebrow plain">THEIR NEXT ADVENTURE STARTS HERE</span><h2>Come for a visit.<br>Leave with a little joy.</h2><p>Meet the possibilities. Ask the questions. Feel the connection.</p></div><span class="cta-mark" aria-hidden="true">✳</span><div class="cta-actions"><button class="button primary" data-visit>Let's plan your visit <span>↗</span></button><p>One small hello. A whole new beginning.</p></div></div></div></section>`;
export const faq=`<div class="faq-list"><details><summary>Which program is right for my child?</summary><p>Our program age ranges are a starting point. Tell us about your child's age and preschool experience, and the school can help you discuss a suitable placement.</p></details><details><summary>Can we visit before deciding?</summary><p>Of course—use “Book a Visit” to send your preferred date. The school will need to confirm availability and the time with you before your visit is booked.</p></details><details><summary>How can I find out about fees and timings?</summary><p>Send an admissions enquiry with the program you are interested in. Ask the school for the current fee structure, available sessions and joining requirements.</p></details><details><summary>What if this is my child's first preschool?</summary><p>Let us know in your enquiry. A first visit is a good time to talk about your child's routine, what helps them feel comfortable and how settling in could work.</p></details><details><summary>Does an enquiry confirm admission?</summary><p>No. An enquiry simply starts a conversation. Program availability, admission steps and any payments are discussed separately with the school.</p></details></div>`;
export const programCards=`<div class="program-grid">${programs.map(p=>`<article class="program-card ${p.color}" id="${p.id}" data-program-age="${p.filter}"><div class="program-card-top"><i class="icon-tile">${icon(p.icon)}</i><span class="age-badge">${p.age}</span></div><h3>${p.name}</h3><p>${p.intro}</p><button class="card-link" data-program="${p.id}" aria-label="Explore ${p.name}">A peek inside <span aria-hidden="true">↗</span></button></article>`).join('')}</div>`;
export function form(prefix){return `<form class="enquiry-form" id="${prefix}-form"><div class="honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="field-row"><label for="${prefix}-name">Your name *<input id="${prefix}-name" name="name" autocomplete="name" required minlength="2" maxlength="100" placeholder="Parent or guardian's name"></label><label for="${prefix}-phone">Phone number *<input id="${prefix}-phone" name="phone" type="tel" autocomplete="tel" required minlength="10" maxlength="20" placeholder="Your contact number"></label></div><label for="${prefix}-email">Email address *<input id="${prefix}-email" name="email" type="email" autocomplete="email" required maxlength="150" placeholder="you@example.com"></label><div class="field-row"><label for="${prefix}-program">Interested in *<select id="${prefix}-program" name="program" required><option value="">Choose a program</option>${programs.map(p=>`<option value="${p.id}">${p.name} (${p.age})</option>`).join('')}<option value="unsure">Help me choose</option></select></label><label for="${prefix}-date">Preferred visit <span class="optional">(optional)</span><input id="${prefix}-date" name="visitDate" type="date"></label></div><label for="${prefix}-message">Anything you'd like to ask? <span class="optional">(optional)</span><textarea id="${prefix}-message" name="message" rows="3" maxlength="1500" placeholder="Tell us what you'd like to know…"></textarea></label><p class="form-help">Please avoid including your child's full name or sensitive details. A preferred date is a request, subject to confirmation.</p><label class="consent"><input type="checkbox" name="consent" required><span>I agree to be contacted about this enquiry and have read the <a href="/privacy">enquiry privacy information</a>.</span></label><div class="form-status" role="status" aria-live="polite" tabindex="-1"></div><button class="button primary" type="submit">Send a little hello <span aria-hidden="true">↗</span></button><p class="form-help">Your enquiry will be saved for the school. No payment is required.</p></form>`;}
export const modals=`<dialog class="modal" id="visit-modal" aria-labelledby="visit-title"><div class="modal-inner"><button class="close-modal" data-close aria-label="Close visit request">×</button><span class="eyebrow plain">LET'S SAY HELLO</span><h2 id="visit-title">A little visit.<br>A big first step.</h2><p class="intro-copy">Send a visit request or ask us about admissions. We're happy to start with your questions.</p>${form('visit')}</div></dialog><dialog class="modal program-detail" id="program-modal" aria-labelledby="program-title"><div class="modal-inner"><button class="close-modal" data-close aria-label="Close program details">×</button><span class="eyebrow plain" id="program-age"></span><h2 id="program-title"></h2><p id="program-description"></p><ul class="program-detail-list" id="program-skills"></ul><p class="form-help">A guide to this stage of learning. Ask the school about current program availability and placement.</p><button class="button primary" id="program-enquire">Ask about this program <span>↗</span></button></div></dialog>`;
export const head=`<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#087b65"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fredoka.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/styles.css">`;
